#---------------------------------#
#      general configuration      #
#---------------------------------#

branches:
  only:
    - master

only_commits:
  files:
    - src\
    - vs2015\

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017

init:
  - git config --global core.autocrlf true

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform:
  - x64
  
configuration: Release

build:
  project: vs2015\dosbox-x.sln
  
after_build:
  - ps : >-
        $shortHash = $env:APPVEYOR_REPO_COMMIT.Substring(0, 7);
        7z a dosbox-x-windows-$shortHash.zip C:\projects\dosbox-x\vs2015\..\bin\x64\Release\changelog.txt;
        7z a dosbox-x-windows-$shortHash.zip C:\projects\dosbox-x\vs2015\..\bin\x64\Release\dosbox.reference.conf;
        7z a dosbox-x-windows-$shortHash.zip C:\projects\dosbox-x\vs2015\..\bin\x64\Release\dosbox-x.exe;
        7z a dosbox-x-windows-$shortHash.zip C:\projects\dosbox-x\vs2015\..\bin\x64\Release\FREECG98.BMP;
  
#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: dosbox-x-windows-*.zip
    name: DOSBox-X Windows Build
